# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  - job: Build
    steps:
      - task: NuGetToolInstaller@1
        displayName: Installing NuGet

      - task: NuGetCommand@2
        displayName: Restoring Nuget packages
        inputs:
          restoreSolution: '$(solution)'

      - task: VSBuild@1
        displayName: Building solution
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:OutDir=$(Build.BinariesDirectory)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      - task: CopyFiles@2
        displayName: Preparing binaries
        inputs:
          SourceFolder: '$(Build.BinariesDirectory)'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        displayName: Publishing binaries
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'Build Output'
          publishLocation: 'Container'

      - task: CopyFiles@2
        displayName: Preparing packages
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: '**/bin/$(buildConfiguration)/**/*.nupkg'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          CleanTargetFolder: true
          flattenFolders: true

      - task: PublishBuildArtifacts@1
        displayName: Publishing packages
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'Packages'
          publishLocation: 'Container'

  - job: Test
    dependsOn: Build
    steps:
      - task: DownloadPipelineArtifact@2
        displayName: Downloading binaries
        inputs:
          buildType: 'current'
          artifactName: 'Binaries'
          targetPath: '$(Pipeline.Workspace)'

      - task: VSTest@2
        displayName: Running unit tests
        inputs:
          testSelector: 'testAssemblies'
          testAssemblyVer2: |
            **\*test*.dll
            !**\*TestAdapter.dll
            !**\obj\**
          searchFolder: '$(Pipeline.Workspace)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          codeCoverageEnabled: true

      - task: PublishTestResults@2
        displayName: Publishing test results
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '**/TEST-*.xml'
          searchFolder: '$(Pipeline.Workspace)'
          mergeTestResults: true

  - job: Publish
    dependsOn: Test
    steps:
      - task: DownloadPipelineArtifact@2
        displayName: Downloading packages
        inputs:
          buildType: 'current'
          artifactName: 'Packages'
          targetPath: '$(Pipeline.Workspace)'

      - task: NuGetCommand@2
        displayName: Publishing packages to feed
        inputs:
          command: 'push'
          packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: '5e504c28-3c5f-442f-b4d7-6b5eeae74624'
          allowPackageConflicts: true
