# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  - master

pool:
  vmImage: "windows-latest"

variables:
  solution: "**/*.sln"
  buildConfiguration: "Release"

jobs:
  - job: Build
    steps:
      - task: NuGetToolInstaller@1
        displayName: Installing NuGet

      - task: DotNetCoreCLI@2
        displayName: Restoring Nuget packages
        inputs:
          command: "restore"
          projects: "$(solution)"

      - task: PowerShell@2
        displayName: Generating version number
        inputs:
          filePath: "$(Build.SourcesDirectory)/build/Update-Version.ps1"
          workingDirectory: "$(Build.SourcesDirectory)"

      - task: DotNetCoreCLI@2
        displayName: Building solution
        inputs:
          command: "build"
          projects: "$(solution)"
          arguments: '-c $(buildConfiguration) -p:PackageVersion="$(PackageVersion)" -p:AssemblyVersion="$(AssemblyVersion)" -p:FileVersion="$(FileVersion)" -p:ProductVersion="$(ProductVersion)" -p:Product="$(ProductName)"'

      - task: CopyFiles@2
        displayName: Preparing binaries
        inputs:
          SourceFolder: "$(Build.BinariesDirectory)"
          Contents: "**"
          TargetFolder: "$(Build.ArtifactStagingDirectory)"

      - task: PublishBuildArtifacts@1
        displayName: Publishing binaries
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "Binaries"
          publishLocation: "Container"

      - task: CopyFiles@2
        displayName: Preparing packages
        inputs:
          SourceFolder: "$(Build.SourcesDirectory)"
          Contents: "**/bin/$(buildConfiguration)/**/*.nupkg"
          TargetFolder: "$(Build.ArtifactStagingDirectory)"
          CleanTargetFolder: true
          flattenFolders: true

      - task: PublishBuildArtifacts@1
        displayName: Publishing packages
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "Packages"
          publishLocation: "Container"

  - job: Test
    dependsOn: Build
    steps:
      - task: DotNetCoreCLI@2
        displayName: Running unit tests
        inputs:
          command: "test"
          projects: "**/*Tests.csproj"
          arguments: '-c $(buildConfiguration) --collect "XPlat Code coverage" -- RunConfiguration.DisableAppDomain=true'

      - task: PublishCodeCoverageResults@1
        displayName: Publishing code coverage results
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: "$(Agent.TempDirectory)/**/coverage.cobertura.xml"

  - job: Publish
    dependsOn: Test
    steps:
      - task: DownloadPipelineArtifact@2
        displayName: Downloading packages
        inputs:
          buildType: "current"
          artifactName: "Packages"
          targetPath: "$(Pipeline.Workspace)"

      - task: DotNetCoreCLI@2
        displayName: Publishing packages to feed
        inputs:
          command: "push"
          packagesToPush: "$(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg"
          nuGetFeedType: "internal"
          publishVstsFeed: "3217e703-6082-4eae-98ab-928df738a396/220f50b0-b82e-4725-bb50-845ac1838fe3"
